name: Android CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.3

      - name: Setup JDK 17
        uses: actions/setup-java@v3.12.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Gradle Dependencies
        uses: actions/cache@v3.3.1
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: gradle-deps-core-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: gradle-deps

      - name: Cache Gradle Build
        uses: actions/cache@v3.3.1
        with:
          path: |
            ~/.gradle/caches/build-cache-*
            ~/.gradle/buildOutputCleanup/cache.properties
          key: gradle-builds-core-${{ github.sha }}
          restore-keys: gradle-builds

      - name: Build with Gradle
        run: |
          bash ./gradlew assemble

      - name: Upload Release APK
        uses: actions/upload-artifact@v3.1.2
        with:
          name: VerixSettings-Release
          path: "app/build/outputs/apk/release/*.apk"

      - name: Upload Debug APK
        uses: actions/upload-artifact@v3.1.2
        with:
          name: VerixSettings-Debug
          path: "app/build/outputs/apk/debug/*.apk"